name: Manually Build Release
on:
    workflow_dispatch:
        inputs:
            versionNumber:
                description: 'Version number of this release'
                required: true
                type: string
jobs:
    build_release:
        name: Build Release
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                language: [ 'python' ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Increment Version Number
              run: ci/new_version.sh ${{inputs.versionNumber}}
            - name: Install Dependencies
              run: pip3 install -r requirements-dev.txt
            - name: Compile and Install
              run: sudo python3 setup.py develop
            - name: Perform Static Codescan Checks
              run: ci/codescan.sh
            - name: Initialize Runtime Code Analysis
              uses: github/codeql-action/init@v2
              with:
                  languages: ${{ matrix.language }}
            - name: Perform Runtime Code Analysis
              uses: github/codeql-action/analyze@v2
            - name: Perfom Secure Code Analysis (Vulnerabilities)
              uses: snyk/actions/python@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: test
            - name: Perform Secure Code Analysis (Secrets)
              uses: trufflesecurity/trufflehog@main
              with:
                  path: ./
                  base: ${{ github.ref_name }}
                  head: HEAD
            - name: Run Unit Tests
              run: ci/test.sh
            - name: Upload release to PyPI
              run: sudo python3 -m twine upload --username=__token__ --password=${{secrets.PYPI_TOKEN}} dist/*
            - name: Create GitHub Release
              run: gh release create v${{inputs.versionNumber}} --latest --generate-notes dist/*
              env:
                  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}