name: Continuous Integration
on:
  push:
  schedule:
    - cron: "00 09 * * *"
jobs:
  continuous_integration:
    name: Continuous Integration
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Runtime Code Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - name: Setup Worker
        run: ci/scripts/setup_worker.sh
      - name: Build Package and Verify
        run: ci/scripts/build.sh
      - name: Perform Static Code Analysis
        run: ci/scripts/codescan.sh
      - name: Perform Runtime Code Analysis
        uses: github/codeql-action/analyze@v2
      - name: Perform Secure Code Analysis (Secrets)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.ref_name }}
          head: HEAD
      - name: Run Unit Tests
        run: ci/scripts/test_runner.sh
      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: |
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/report.xml
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/coverage.xml
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/pytest.log
          if-no-files-found: ignore
          retention-days: 1
