name: Continuous Integration
on:
  pull_request:
    branches:
    - master
  push:
  schedule:
    - cron: "00 09 * * *"
jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Worker
        run: ci/scripts/setup_worker.sh
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Build Package and Verify
        run: ci/scripts/build.sh
      - name: Typing Check
        run: ci/scripts/codescan.sh mypy
      - name: Code Quality Check
        run: ci/scripts/codescan.sh flake8
      - name: Dependency Security Check
        run: ci/scripts/codescan.sh safety
      - name: Formatting Check
        run: ci/scripts/codescan.sh black
      - name: Upload Codescan Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: codescan-test-report
          path: |
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/codescan_logs/*.log
          if-no-files-found: ignore
          retention-days: 1

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Worker
        run: ci/scripts/setup_worker.sh
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Build Package and Verify
        run: ci/scripts/build.sh
      - name: Run Unit Tests
        run: ci/scripts/test_runner.sh
      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: |
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/report.xml
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/coverage.xml
            /home/runner/work/Flask-OpenAPI/Flask-OpenAPI/ci/tests/pytest.log
          if-no-files-found: ignore
          retention-days: 1