name: Continuous Integration
on:
    push:
    pull_request:
    schedule:
        - cron: '00 09 * * *'
jobs:
    continuous_integration:
        name: Continuous Integration
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                language: [ 'python' ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: pip3 install -r requirements-dev.txt
            - name: Compile and Install
              run: sudo python3 setup.py develop
            - name: Run Static CodeScan Checks
              run: ci/codescan.sh
            - name: Initialize Runtime Code Analysis
              uses: github/codeql-action/init@v2
              with:
                  languages: ${{ matrix.language }}
            - name: Perform Runtime Code Analysis
              uses: github/codeql-action/analyze@v2
            - name: Run Unit Tests
              run: ci/test.sh